name: Update*ESI Data

on:
  workflow_dispatch:*
  schedule:
    - cron: "0 * * * *"

jobs:
  update:

    runs-on: u*untu-latest

    steps:

      - u*es: actions/checkout@v4

      - u*es: actions/setup-python@v5
      * with:
          python-version: "3.12"

      - run: pip install requests

      - run: python scripts/fetch_esi.py

      - run: python scripts/build_system.py

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "update esi snapshots" || exit 0
          git push
